name: 'electric_quickstart'

services:
  electric:
    image: docker.io/electricsql/electric:latest
    # env file contains DATABASE_URL
    env_file:
      - .dev.vars
    environment:
      ELECTRIC_INSECURE: true
    ports:
      - '3000:3000'
