/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMealRouteImport } from './routes/_app.meal'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppMealAddRouteImport } from './routes/_app.meal.add'
import { Route as AppMealMealIdRouteImport } from './routes/_app.meal.$mealId'
import { Route as AppCalendarAddRouteImport } from './routes/_app.calendar.add'
import { Route as AppCalendarMealIdRouteImport } from './routes/_app.calendar.$mealId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMealRoute = AppMealRouteImport.update({
  id: '/meal',
  path: '/meal',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppMealAddRoute = AppMealAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppMealRoute,
} as any)
const AppMealMealIdRoute = AppMealMealIdRouteImport.update({
  id: '/$mealId',
  path: '/$mealId',
  getParentRoute: () => AppMealRoute,
} as any)
const AppCalendarAddRoute = AppCalendarAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppCalendarRoute,
} as any)
const AppCalendarMealIdRoute = AppCalendarMealIdRouteImport.update({
  id: '/$mealId',
  path: '/$mealId',
  getParentRoute: () => AppCalendarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRouteWithChildren
  '/meal': typeof AppMealRouteWithChildren
  '/calendar/$mealId': typeof AppCalendarMealIdRoute
  '/calendar/add': typeof AppCalendarAddRoute
  '/meal/$mealId': typeof AppMealMealIdRoute
  '/meal/add': typeof AppMealAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRouteWithChildren
  '/meal': typeof AppMealRouteWithChildren
  '/calendar/$mealId': typeof AppCalendarMealIdRoute
  '/calendar/add': typeof AppCalendarAddRoute
  '/meal/$mealId': typeof AppMealMealIdRoute
  '/meal/add': typeof AppMealAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRouteWithChildren
  '/_app/meal': typeof AppMealRouteWithChildren
  '/_app/calendar/$mealId': typeof AppCalendarMealIdRoute
  '/_app/calendar/add': typeof AppCalendarAddRoute
  '/_app/meal/$mealId': typeof AppMealMealIdRoute
  '/_app/meal/add': typeof AppMealAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/meal'
    | '/calendar/$mealId'
    | '/calendar/add'
    | '/meal/$mealId'
    | '/meal/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/meal'
    | '/calendar/$mealId'
    | '/calendar/add'
    | '/meal/$mealId'
    | '/meal/add'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/calendar'
    | '/_app/meal'
    | '/_app/calendar/$mealId'
    | '/_app/calendar/add'
    | '/_app/meal/$mealId'
    | '/_app/meal/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/meal': {
      id: '/_app/meal'
      path: '/meal'
      fullPath: '/meal'
      preLoaderRoute: typeof AppMealRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meal/add': {
      id: '/_app/meal/add'
      path: '/add'
      fullPath: '/meal/add'
      preLoaderRoute: typeof AppMealAddRouteImport
      parentRoute: typeof AppMealRoute
    }
    '/_app/meal/$mealId': {
      id: '/_app/meal/$mealId'
      path: '/$mealId'
      fullPath: '/meal/$mealId'
      preLoaderRoute: typeof AppMealMealIdRouteImport
      parentRoute: typeof AppMealRoute
    }
    '/_app/calendar/add': {
      id: '/_app/calendar/add'
      path: '/add'
      fullPath: '/calendar/add'
      preLoaderRoute: typeof AppCalendarAddRouteImport
      parentRoute: typeof AppCalendarRoute
    }
    '/_app/calendar/$mealId': {
      id: '/_app/calendar/$mealId'
      path: '/$mealId'
      fullPath: '/calendar/$mealId'
      preLoaderRoute: typeof AppCalendarMealIdRouteImport
      parentRoute: typeof AppCalendarRoute
    }
  }
}

interface AppCalendarRouteChildren {
  AppCalendarMealIdRoute: typeof AppCalendarMealIdRoute
  AppCalendarAddRoute: typeof AppCalendarAddRoute
}

const AppCalendarRouteChildren: AppCalendarRouteChildren = {
  AppCalendarMealIdRoute: AppCalendarMealIdRoute,
  AppCalendarAddRoute: AppCalendarAddRoute,
}

const AppCalendarRouteWithChildren = AppCalendarRoute._addFileChildren(
  AppCalendarRouteChildren,
)

interface AppMealRouteChildren {
  AppMealMealIdRoute: typeof AppMealMealIdRoute
  AppMealAddRoute: typeof AppMealAddRoute
}

const AppMealRouteChildren: AppMealRouteChildren = {
  AppMealMealIdRoute: AppMealMealIdRoute,
  AppMealAddRoute: AppMealAddRoute,
}

const AppMealRouteWithChildren =
  AppMealRoute._addFileChildren(AppMealRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRouteWithChildren
  AppMealRoute: typeof AppMealRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRouteWithChildren,
  AppMealRoute: AppMealRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
