/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppMealTypeRouteImport } from './routes/_app.meal-type'
import { Route as AppMealRouteImport } from './routes/_app.meal'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as ApiSyncMeal_typeRouteImport } from './routes/api.sync.meal_type'
import { Route as ApiSyncMealRouteImport } from './routes/api.sync.meal'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppMealAddRouteImport } from './routes/_app.meal.add'
import { Route as AppMealMealIdRouteImport } from './routes/_app.meal.$mealId'
import { Route as AppMealTypeAddRouteImport } from './routes/_app.meal-type.add'
import { Route as AppMealTypeMealTypeIdRouteImport } from './routes/_app.meal-type.$mealTypeId'
import { Route as AppCalendarAddRouteImport } from './routes/_app.calendar.add'
import { Route as AppCalendarMealIdRouteImport } from './routes/_app.calendar.$mealId'

const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMealTypeRoute = AppMealTypeRouteImport.update({
  id: '/meal-type',
  path: '/meal-type',
  getParentRoute: () => AppRoute,
} as any)
const AppMealRoute = AppMealRouteImport.update({
  id: '/meal',
  path: '/meal',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const ApiSyncMeal_typeRoute = ApiSyncMeal_typeRouteImport.update({
  id: '/api/sync/meal_type',
  path: '/api/sync/meal_type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncMealRoute = ApiSyncMealRouteImport.update({
  id: '/api/sync/meal',
  path: '/api/sync/meal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMealAddRoute = AppMealAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppMealRoute,
} as any)
const AppMealMealIdRoute = AppMealMealIdRouteImport.update({
  id: '/$mealId',
  path: '/$mealId',
  getParentRoute: () => AppMealRoute,
} as any)
const AppMealTypeAddRoute = AppMealTypeAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppMealTypeRoute,
} as any)
const AppMealTypeMealTypeIdRoute = AppMealTypeMealTypeIdRouteImport.update({
  id: '/$mealTypeId',
  path: '/$mealTypeId',
  getParentRoute: () => AppMealTypeRoute,
} as any)
const AppCalendarAddRoute = AppCalendarAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppCalendarRoute,
} as any)
const AppCalendarMealIdRoute = AppCalendarMealIdRouteImport.update({
  id: '/$mealId',
  path: '/$mealId',
  getParentRoute: () => AppCalendarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/calendar': typeof AppCalendarRouteWithChildren
  '/meal': typeof AppMealRouteWithChildren
  '/meal-type': typeof AppMealTypeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/calendar/$mealId': typeof AppCalendarMealIdRoute
  '/calendar/add': typeof AppCalendarAddRoute
  '/meal-type/$mealTypeId': typeof AppMealTypeMealTypeIdRoute
  '/meal-type/add': typeof AppMealTypeAddRoute
  '/meal/$mealId': typeof AppMealMealIdRoute
  '/meal/add': typeof AppMealAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/meal': typeof ApiSyncMealRoute
  '/api/sync/meal_type': typeof ApiSyncMeal_typeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/calendar': typeof AppCalendarRouteWithChildren
  '/meal': typeof AppMealRouteWithChildren
  '/meal-type': typeof AppMealTypeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/calendar/$mealId': typeof AppCalendarMealIdRoute
  '/calendar/add': typeof AppCalendarAddRoute
  '/meal-type/$mealTypeId': typeof AppMealTypeMealTypeIdRoute
  '/meal-type/add': typeof AppMealTypeAddRoute
  '/meal/$mealId': typeof AppMealMealIdRoute
  '/meal/add': typeof AppMealAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/meal': typeof ApiSyncMealRoute
  '/api/sync/meal_type': typeof ApiSyncMeal_typeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/logo': typeof LogoRoute
  '/_app/calendar': typeof AppCalendarRouteWithChildren
  '/_app/meal': typeof AppMealRouteWithChildren
  '/_app/meal-type': typeof AppMealTypeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/calendar/$mealId': typeof AppCalendarMealIdRoute
  '/_app/calendar/add': typeof AppCalendarAddRoute
  '/_app/meal-type/$mealTypeId': typeof AppMealTypeMealTypeIdRoute
  '/_app/meal-type/add': typeof AppMealTypeAddRoute
  '/_app/meal/$mealId': typeof AppMealMealIdRoute
  '/_app/meal/add': typeof AppMealAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/meal': typeof ApiSyncMealRoute
  '/api/sync/meal_type': typeof ApiSyncMeal_typeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logo'
    | '/calendar'
    | '/meal'
    | '/meal-type'
    | '/auth/login'
    | '/calendar/$mealId'
    | '/calendar/add'
    | '/meal-type/$mealTypeId'
    | '/meal-type/add'
    | '/meal/$mealId'
    | '/meal/add'
    | '/api/auth/$'
    | '/api/sync/meal'
    | '/api/sync/meal_type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logo'
    | '/calendar'
    | '/meal'
    | '/meal-type'
    | '/auth/login'
    | '/calendar/$mealId'
    | '/calendar/add'
    | '/meal-type/$mealTypeId'
    | '/meal-type/add'
    | '/meal/$mealId'
    | '/meal/add'
    | '/api/auth/$'
    | '/api/sync/meal'
    | '/api/sync/meal_type'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/logo'
    | '/_app/calendar'
    | '/_app/meal'
    | '/_app/meal-type'
    | '/auth/login'
    | '/_app/calendar/$mealId'
    | '/_app/calendar/add'
    | '/_app/meal-type/$mealTypeId'
    | '/_app/meal-type/add'
    | '/_app/meal/$mealId'
    | '/_app/meal/add'
    | '/api/auth/$'
    | '/api/sync/meal'
    | '/api/sync/meal_type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LogoRoute: typeof LogoRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSyncMealRoute: typeof ApiSyncMealRoute
  ApiSyncMeal_typeRoute: typeof ApiSyncMeal_typeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/meal-type': {
      id: '/_app/meal-type'
      path: '/meal-type'
      fullPath: '/meal-type'
      preLoaderRoute: typeof AppMealTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meal': {
      id: '/_app/meal'
      path: '/meal'
      fullPath: '/meal'
      preLoaderRoute: typeof AppMealRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/sync/meal_type': {
      id: '/api/sync/meal_type'
      path: '/api/sync/meal_type'
      fullPath: '/api/sync/meal_type'
      preLoaderRoute: typeof ApiSyncMeal_typeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/meal': {
      id: '/api/sync/meal'
      path: '/api/sync/meal'
      fullPath: '/api/sync/meal'
      preLoaderRoute: typeof ApiSyncMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/meal/add': {
      id: '/_app/meal/add'
      path: '/add'
      fullPath: '/meal/add'
      preLoaderRoute: typeof AppMealAddRouteImport
      parentRoute: typeof AppMealRoute
    }
    '/_app/meal/$mealId': {
      id: '/_app/meal/$mealId'
      path: '/$mealId'
      fullPath: '/meal/$mealId'
      preLoaderRoute: typeof AppMealMealIdRouteImport
      parentRoute: typeof AppMealRoute
    }
    '/_app/meal-type/add': {
      id: '/_app/meal-type/add'
      path: '/add'
      fullPath: '/meal-type/add'
      preLoaderRoute: typeof AppMealTypeAddRouteImport
      parentRoute: typeof AppMealTypeRoute
    }
    '/_app/meal-type/$mealTypeId': {
      id: '/_app/meal-type/$mealTypeId'
      path: '/$mealTypeId'
      fullPath: '/meal-type/$mealTypeId'
      preLoaderRoute: typeof AppMealTypeMealTypeIdRouteImport
      parentRoute: typeof AppMealTypeRoute
    }
    '/_app/calendar/add': {
      id: '/_app/calendar/add'
      path: '/add'
      fullPath: '/calendar/add'
      preLoaderRoute: typeof AppCalendarAddRouteImport
      parentRoute: typeof AppCalendarRoute
    }
    '/_app/calendar/$mealId': {
      id: '/_app/calendar/$mealId'
      path: '/$mealId'
      fullPath: '/calendar/$mealId'
      preLoaderRoute: typeof AppCalendarMealIdRouteImport
      parentRoute: typeof AppCalendarRoute
    }
  }
}

interface AppCalendarRouteChildren {
  AppCalendarMealIdRoute: typeof AppCalendarMealIdRoute
  AppCalendarAddRoute: typeof AppCalendarAddRoute
}

const AppCalendarRouteChildren: AppCalendarRouteChildren = {
  AppCalendarMealIdRoute: AppCalendarMealIdRoute,
  AppCalendarAddRoute: AppCalendarAddRoute,
}

const AppCalendarRouteWithChildren = AppCalendarRoute._addFileChildren(
  AppCalendarRouteChildren,
)

interface AppMealRouteChildren {
  AppMealMealIdRoute: typeof AppMealMealIdRoute
  AppMealAddRoute: typeof AppMealAddRoute
}

const AppMealRouteChildren: AppMealRouteChildren = {
  AppMealMealIdRoute: AppMealMealIdRoute,
  AppMealAddRoute: AppMealAddRoute,
}

const AppMealRouteWithChildren =
  AppMealRoute._addFileChildren(AppMealRouteChildren)

interface AppMealTypeRouteChildren {
  AppMealTypeMealTypeIdRoute: typeof AppMealTypeMealTypeIdRoute
  AppMealTypeAddRoute: typeof AppMealTypeAddRoute
}

const AppMealTypeRouteChildren: AppMealTypeRouteChildren = {
  AppMealTypeMealTypeIdRoute: AppMealTypeMealTypeIdRoute,
  AppMealTypeAddRoute: AppMealTypeAddRoute,
}

const AppMealTypeRouteWithChildren = AppMealTypeRoute._addFileChildren(
  AppMealTypeRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRouteWithChildren
  AppMealRoute: typeof AppMealRouteWithChildren
  AppMealTypeRoute: typeof AppMealTypeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRouteWithChildren,
  AppMealRoute: AppMealRouteWithChildren,
  AppMealTypeRoute: AppMealTypeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LogoRoute: LogoRoute,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSyncMealRoute: ApiSyncMealRoute,
  ApiSyncMeal_typeRoute: ApiSyncMeal_typeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
